# Generated by Django 5.1.7 on 2025-04-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='employer',
            new_name='company',
        ),
    ]
