# Generated by Django 5.1.7 on 2025-04-30 14:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0002_rename_employer_job_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000)]),
        ),
        migrations.CreateModel(
            name='JobPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=50)),
                ('payer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_currency', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='job_portal.job')),
            ],
        ),
    ]
