# Generated by Django 5.1.7 on 2025-05-01 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0003_alter_job_salary_jobpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.AddField(
            model_name='job',
            name='additional_questions',
            field=models.TextField(blank=True, help_text='Enter questions separated by new lines.'),
        ),
        migrations.AddField(
            model_name='job',
            name='company_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='expected_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_required',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='job_language',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('hindi', 'Hindi'), ('spanish', 'Spanish'), ('french', 'French'), ('german', 'German'), ('mandarin', 'Mandarin'), ('tamil', 'Tamil'), ('telugu', 'Telugu'), ('bengali', 'Bengali'), ('other', 'Other')], default='english', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='job_location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_portal.location'),
        ),
        migrations.AddField(
            model_name='job',
            name='number_of_people',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='work_environment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='work_location_type',
            field=models.CharField(choices=[('onsite', 'Onsite'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='onsite', max_length=10),
        ),
    ]
