# Generated by Django 5.1.7 on 2025-05-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0004_remove_job_location_job_additional_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='additional_questions',
            field=models.TextField(blank=True, help_text='Enter questions separated by new lines.', null=True),
        ),
    ]
