# Generated by Django 5.1.7 on 2025-05-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0005_alter_job_additional_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpayment',
            name='payment_status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=50),
        ),
    ]
