# Generated by Django 5.1.7 on 2025-05-02 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0007_savedjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applied_date',
            new_name='applied_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.AddField(
            model_name='application',
            name='custom_answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='job_seeker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_portal.jobseekerprofile'),
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_portal.job'),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to='application_resumes/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=20),
        ),
    ]
