# Generated by Django 5.1.7 on 2025-05-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0008_rename_applied_date_application_applied_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(null=True, upload_to='application_resumes/'),
        ),
    ]
