# Generated by Django 5.1.7 on 2025-05-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0009_alter_application_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='experiences',
            field=models.ManyToManyField(blank=True, to='job_portal.experience'),
        ),
    ]
