# Generated by Django 5.1.7 on 2025-05-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0010_experience_jobseekerprofile_experiences'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.PositiveIntegerField(),
        ),
    ]
