# Generated by Django 5.1.7 on 2025-05-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0011_jobseekerprofile_about_alter_experience_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='current_applicants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job_seeker', 'job')},
        ),
    ]
