# Generated by Django 5.1.7 on 2025-05-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0012_job_current_applicants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.CharField(blank=True, choices=[(1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='field',
            field=models.CharField(choices=[('computer_science', 'Computer Science'), ('information_technology', 'Information Technology'), ('engineering', 'Engineering'), ('business_administration', 'Business Administration'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('economics', 'Economics'), ('psychology', 'Psychology'), ('education', 'Education'), ('biology', 'Biology'), ('chemistry', 'Chemistry'), ('physics', 'Physics'), ('mathematics', 'Mathematics'), ('english_literature', 'English Literature'), ('journalism', 'Journalism'), ('law', 'Law'), ('medicine', 'Medicine'), ('nursing', 'Nursing'), ('architecture', 'Architecture'), ('other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.CharField(choices=[(1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025')], max_length=100, null=True),
        ),
    ]
