# Generated by Django 5.1.7 on 2025-05-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0013_alter_education_end_year_alter_education_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='currently_enrolled',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='field',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Information Technology', 'Information Technology'), ('Engineering', 'Engineering'), ('Business Administration', 'Business Administration'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Economics', 'Economics'), ('Psychology', 'Psychology'), ('Education', 'Education'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Mathematics', 'Mathematics'), ('English Literature', 'English Literature'), ('Journalism', 'Journalism'), ('Law', 'Law'), ('Medicine', 'Medicine'), ('Nursing', 'Nursing'), ('Architecture', 'Architecture'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
