# Generated by Django 5.1.7 on 2025-05-03 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0014_alter_education_currently_enrolled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='school_address',
        ),
        migrations.AddField(
            model_name='education',
            name='school_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_portal.schooladdress'),
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='education',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='education',
            field=models.ManyToManyField(blank=True, to='job_portal.education'),
        ),
    ]
