# Generated by Django 5.1.7 on 2025-05-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0018_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='education',
            field=models.ManyToManyField(blank=True, related_name='education', to='job_portal.education'),
        ),
    ]
